### PR TITLE
make lumina look better in the dialog

### PR DESCRIPTION
**Pull request by kapzduke**

### CODE REVIEW

**Review by Slotterleet — CHANGES_REQUESTED** [review]
This actually makes zooming in or out impossible once you zoom out enough.

**Comment by kapzduke** [comment]
no how do i undo this

**Review by Slotterleet — COMMENTED** [review]
Set `camRadius` to 0.4f and I'll merge this.

**Review by Slotterleet — APPROVED** [review]

**Comment by Slotterleet** [comment]
nevermind

p.s. i can't fix this stupid check fail

**Pull request merged**
