### PR TITLE
rather luminous tweaks

### PR DESCRIPTION
**Pull request by kapzduke**

### CODE REVIEW

**Comment by Slotterleet** [comment]
13 freaking errors. No wonder the check had failed multiple times.

**Comment by kapzduke** [comment]
> 13 freaking errors. No wonder the check had failed multiple times.

it has been reduced to one but idk how to fix it

**Comment by Slotterleet** [comment]
You haven't defined `drillBase`.

**Comment by Slotterleet** [comment]
it's `drillBase` first letter lowercase. `DrillBase` is already imported.

**Pull request merged**
